<?php
/**
 * Created by PhpStorm.
 * User: cadistortion
 * Date: 4/13/18
 * Time: 11:39 AM
 */

namespace App\Modules;

use App\Modules\Mvc\MvcModule;
use App\Modules\Mvc\Routing\Request;
use App\Modules\Mvc\Routing\RequestInterface;
use App\Modules\Mvc\Routing\Response;
use PHPUnit\Framework\TestCase;

class ModuleArgumentTest extends TestCase
{
    protected $request;
    protected $response;

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->request = $this->createMock(Request::class);
        $this->request->expects($this->any())->method('getMethod')->willReturn('GET');
        $this->request->expects($this->any())
            ->method('getUri')
            ->willReturn('localhost:8080/Home/withViewModel/1');
        $this->request->expects($this->any())
            ->method('getDomain')
            ->willReturn('localhost:8080');

        $this->response = $this->createMock(Response::class);
    }

    public function testThatItImplementsNeededInterface()
    {


        $module_result = null;

        $module_argument = new ModuleArgument([
            'request' => $this->request,
            'response' => $this->response
        ]);
        $this->assertNotNull($module_argument);
        $this->assertInstanceOf(ModuleArgumentInterface::class, $module_argument);

        return $module_argument;
    }

    /**
     * @depends testThatItImplementsNeededInterface
     */
    public function testInterfaceMethodsAreImplemented(ModuleArgument $argument)
    {
        $this->assertNotNull($argument->getResponse());
        $this->assertNotNull($argument->getRequest());
        $this->assertTrue(method_exists($argument, 'getModuleResult'));
    }

    public function testThatModuleArgumentWillBeConstructedWithModuleResult()
    {
        $module_result = $this->createMock(ModuleResult::class);
        $module_argument = new ModuleArgument([
            'request' => $this->request,
            'response' => $this->response,
            'result' => $module_result
        ]);

        $this->assertNotNull($module_argument->getModuleResult());
        $this->assertInstanceOf(ModuleResultInterface::class, $module_argument->getModuleResult());
    }

    public function testModuleArgumentWillReturnArrayOfPreviousResults()
    {
        $subject_module = $this->createMock(MvcModule::class);
        $subject_module->method('getNameOfModule')->willReturn(MvcModule::class);
        $module_result = $this->createMock(ModuleResultInterface::class);
        $module_result->method('getSubjectModule')->willReturn($subject_module);

        $module_argument = new ModuleArgument([
            'request' => $this->request,
            'response' => $this->response,
            'result' => $module_result
        ]);

        $module_argument->addResult($module_result);

        $this->assertEquals(1, count($module_argument->getAllResults()));
        $this->assertEquals(MvcModule::class, $module_argument->getAllResults()[0]->getSubjectModule()->getNameOfModule());
    }


}
