<?php
/**
 * Created by PhpStorm.
 * User: cadistortion
 * Date: 4/4/18
 * Time: 7:26 PM
 */

namespace App\Modules\Mvc\Controller;


use const App\Config\SEGMENT_VIEWS_LAST_NAMESPACE;
use App\Modules\Mvc\View\ViewResultInterface;

final class ViewResult extends AbstractActionResult implements ViewResultInterface
{
    private $viewName;
    private $viewModel;
    private $renderer;

    public function __construct(array $init_arr)
    {
        $this->viewName = $init_arr['view_name'];
        $this->viewModel = $init_arr['view_model'];
        $this->renderer = $init_arr['renderer'];
    }

    public function getViewName()
    {
        return $this->viewName;
    }

    public function getViewModel()
    {
        return $this->viewModel;
    }

    public function getRenderedContent()
    {
        if (empty($this->renderedContent)){
            $this->renderedContent = $this->renderer->render($this->viewName, $this->viewModel);
        }
        return parent::getRenderedContent(); // TODO: Change the autogenerated stub
    }
}