<?php
/**
 * Created by PhpStorm.
 * User: NyoNor
 * Date: 3/22/2018
 * Time: 6:53 PM
 */

namespace App\Autoload;


use App\Config\Config;

final class SegmentAutoloader extends Autoloader
{
    private $projectSegments;

    public function __construct(array $project_segments)
    {
        $require_array = self::getProjectSegmentsToRequireArray($project_segments);
        parent::__construct($require_array);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    private static function getProjectSegmentsToRequireArray($project_segments) : array
    {
        $result = [];

        foreach ($project_segments as $segment_name => $option) {
            foreach ($option['autoload_data'] as $namespace => $path){
                $result[$namespace] = $path;
            }
        }

        return $result;
    }
}